    <section class="contenedor website" id="website">
        <div class="contenedor-textos-main">
            <h2 class="titulo left corregido">Acompañamos tu proyecto de principio a fin</h2>
            <p class="parrafo">AmigaTech es una cooperativa experta en diseño y desarrollo. 
                Traemos productos digitales desde la validación hasta el éxito 
                y ofrecemos servicios de hosting y mantenimiento para seguir acompañándote. </p>
        </div>
        <img src="../../resources/images/acompañamos.svg" alt="">
    </section>

    <section class="cards contenedor">
        <h2 class="titulo">Nuestros servicios</h2>
        <div class="content-cards">
            <a href="#dyd" class="card-btn">
                <article class="card">
                    <i class="fa-solid fa-palette"></i>
                    <h3>Diseño</h3>
                </article>
            </a>
            <a href="#dyd" class="card-btn">
                <article class="card">
                    <i class="fa-solid fa-code"></i>
                    <h3>Desarrollo</h3>
                </article>
            </a>
            <a href="#mant" class="card-btn">
                <article class="card">
                    <i class="fa-solid fa-wrench"></i>
                    <h3>Mantenimiento</h3>
                </article>
            </a>
        </div>
    </section>

    <section class="info dyd">
        <a href="../services/services.php">
            <img src="../../resources/images/CSS_Flatline.svg" alt="">
        </a>
        <h2 id="dyd">Diseño y desarrollo</h2>
        <div class="dyd-texto">
            <p class="parrafo">Si tienes una idea o si formas parte de un proyecto que busca 
                presencia en la web, AmigaTech puede ayudarte. Elaboramos sitios web modernos 
                y responsivos. Nos enfocamos en la experiencia del usuario y en una 
                interfaz amigable. También apoyamos proyectos que busquen innovar con 
                el diseño, dándole una personalidad propia a su sitio.</p>
        </div>
    </section>

    <h2 id="mant">¿Tienes un sitio web obsoleto?</h2>
    <section class="mant">
    <img src="../../resources/images/Web Developer_Flatline-cropped.svg" alt=""/>
      <div class="contenedor-textos-main">
            <p class="parrafo"></br>
                <a class="link-txt" href="../services/services.php">¡Conocé nuestros servicios de mantenimiento!</a></br></br>
                Trabajemos juntos para reformar sitios existentes 
                que presenten problemas de funcionamiento y también 
                para renovar aquellas que tengan un diseño anticuado. 
            </br></br>
                ¿Quieres integrar nuevas funciones a tu sitio web?
                AmigaTech trabajará contigo para realizarlo de manera eficaz 
            </p>
        </div>
        
    </section>   
  

    <section class="portfolio">
            <h2 class="titulo">Portfolio: Nuestro trabajo</h2>
            <div class="container-fluid">
                <div id="myCarousel" class="carousel slide" data-bs-interval="2000" data-bs-ride="true" data-bs-pause="false">
                <!--Indicators-->
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"
                        aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1"
                        aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2"
                        aria-label="Slide 3"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3"
                        aria-label="Slide 4"></button>
                </div>
                <!--Slides-->
                <div class="carousel-inner" id="carouselId">
                    <div class="carousel-item active">
                        <img src="../../resources/images/img1.png" class="d-block w-100 image-fluid" alt="First slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>First slide label</h5>
                            <p>Some representative placeholder content for the first slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../resources/images/img2.png" class="d-block w-100 image-fluid" alt="Second slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Second slide label</h5>
                            <p>Some representative placeholder content for the second slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../resources/images/img3.png" class="d-block w-100 image-fluid" alt="Third slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Third slide label</h5>
                            <p>Some representative placeholder content for the third slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../resources/images/img4.png" class="d-block w-100 image-fluid" alt="Fourth slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Fourth slide label</h5>
                            <p>Some representative placeholder content for the fourth slide.</p>
                        </div>
                    </div>
                </div>
                <!--Left and right controls-->
                <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#myCarousel"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
    </section>


    <section class="info-last">
        <div class="last-section">
            <div class="contenedor-textos-main">
                <h2 class="titulo left">¿Cómo trabajamos?</h2>
                <p class="parrafo">Los principios de AmigaTech son el <span class="highlight">desarrollo</span> 
                    apuntado a la <span class="highlight">experiencia del usuario</span> 
                    y el <span class="highlight">trabajo enfocado en el cliente</span></p></br>
                <p class="parrafo" >Nuestro framework o entorno de trabajo es SCRUM, 
                    un marco de desarrollo adaptable, que permite implementar 
                    fácilmente cambios al proyecto, ajustandose a las necesidades 
                    del cliente. SCRUM permite desarrollar proyectos con mayor 
                    escalabilidad. </br></br>
                    <a class="link-txt" href="../aboutUs/aboutUs.php">¡Conocenos!</a></br></br>
                </p>
                
            </div>
            <img src="../../resources/images/scrum.svg" alt="">
        </div>
    </section>