 <header class="welcome">
       <div class="textos-welcome">
            <h1>Creamos el mejor sitio web para ti</h1>
            <p>Somos una cooperativa de 
                <span class="highlight">diseño</span>,
                <span class="highlight">desarollo</span> </br> &
                <span class="highlight">mantenimiento</span> 
                de páginas web </p>
                <a href="#website">
                    <i class="fa-solid fa-angle-down"></i>
                </a>
        </div>
    </header>