    <nav>
        <input type="checkbox" id="check">
        <label for="check" class="hamburger">
            <i class="fa-solid fa-bars"></i>
        </label>
        <label class="CoopName"><a href="../home/index.php" aria-hidden="true">AmigaTech</a></label>
            <ul>
                <li><a href="../services/services.php">Servicios</a></li>
                <li><a href="../products/products.php">Productos</a></li>
                <li><a href="../aboutUs/aboutUs.php">Equipo</a></li>
                <li class="contactUs"><a href="#contacto">Contacto</a></li>
            </ul>
    </nav>
