<h2 class="titulo about">Conoce nuestra cooperativa</h2>
<section class="contenedor aboutUs">
    
    <div class="aboutUs-textos">
        <p class="parrafo">AmigaTech es una cooperativa de desarrollo, 
             diseño y mantenimiento de software enfocado en páginas web. 
             Trabajamos con múltiples herramientas para satisfacer todas las 
             demandas de los clientes y contamos con un equipo con conocimientos 
             de frontend, backend y diseño gráfico. Elaboramos sitios web modernos 
             y responsivos enfocados en la experiencia del usuario y con una interfaz 
             amigable, mientras sostenemos un entorno de trabajo inclusivo, horizontal y cooperativo.
        </p>
    </div>
    <img src="../../resources/images/team.svg" alt="">
</section>