

<section class="services-diseño">
    <div class="services-texto">
        <h2 class="titulo">Diseño y desarollo</h2>
        <p class="parrafo">Elaboramos sitios web modernos, responsivos y enfocados en la experiencia 
            del usuario. Desarrollo full-stack; utilizamos herramientas static como HTML5, CSS y JS 
            para crear sitios web dinámicos con PHP y Laravel, incorporamos Bootstrap y Vue.js 
            a nuestras herramientas. 
            Tambien hacemos sitios o portales con WordPress y Drupal.  
        </p>
    </div>
    <div class="brands-resp">
        <div class="services-brands">
            <ul>
                <li><i class="fa-brands fa-html5"></i> HTML5</li>
                <li><i class="fa-brands fa-css3-alt"></i> CSS</li>
                <li><i class="fa-brands fa-js"></i> JavaSript</li>
                <li><i class="fa-brands fa-vuejs"></i> Vue.js</li>
            </ul>
        </div>
        <div class="services-brands">
            <ul>
                <li><i class="fa-brands fa-bootstrap"></i> Bootstrap</li>
                <li><i class="fa-brands fa-php"></i> PHP y MySQL</li>
                <li><i class="fa-brands fa-wordpress"></i> Wordpress</li>
                <li><i class="fa-brands fa-drupal"></i> Drupal</li>
            </ul>
        </div>
    </div>
</section>
<section class="services-mantenimiento">
    <div class="mantenimiento-texto">
        <h2>Mantenimiento</h2>
        <p class="parrafo">
        Ofrecemos servicios extra de mantenimiento y de hosting para el software 
        que desarrollamos. También renovamos sitios que tengan un diseño anticuado, 
        implementando tecnologías modernas y funciones amigables al usuario.
        </p>
    </div>
    <div class="mantenimiento-img">
        <img src="../../resources/images/Maintenance_Flatline.svg" alt="">
    </div>
</section>