
<section class="contenedor">
    <div class="contenedor-textos-main">
        <h2 class="titulo">Conocé nuestro portfolio</h2>
    </div>
    <div class="container-fluid">
                <div id="myCarousel" class="carousel slide"  style="padding-left: 10px;" data-bs-interval="4000" data-bs-ride="true" data-bs-pause="false">
                <!--Indicators-->
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"
                        aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1"
                        aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2"
                        aria-label="Slide 3"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3"
                        aria-label="Slide 4"></button>
                </div>
                <!--Slides-->
                <div class="carousel-inner" id="carouselId">
                    <div class="carousel-item active">
                        <img src="../../resources/images/img1.png" class="d-block w-100 image-fluid" alt="First slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>First slide label</h5>
                            <p>Some representative placeholder content for the first slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../resources/images/img2.png" class="d-block w-100 image-fluid" alt="Second slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Second slide label</h5>
                            <p>Some representative placeholder content for the second slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../resources/images/img3.png" class="d-block w-100 image-fluid" alt="Third slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Third slide label</h5>
                            <p>Some representative placeholder content for the third slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../resources/images/img4.png" class="d-block w-100 image-fluid" alt="Fourth slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Fourth slide label</h5>
                            <p>Some representative placeholder content for the fourth slide.</p>
                        </div>
                    </div>
                </div>
                <!--Left and right controls-->
                <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#myCarousel"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
    </div>
</section>